name = "meadow"
author = "broccoli"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec532ff70c0de14e9b96c8f2a5b75ac6be0814ad8009624588d55cfb137e5bc2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
