name = "meadow"
author = "broccoli"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85dd08418afd34d949487cc47207bc9368890cb3e795e6e470308e98ecefd08f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
