name = "meadow"
author = "broccoli"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f3481731cbbcc475f5897848151c747f35417ce6db50c620b38828033ab71e7"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
