name = "meadow"
author = "broccoli"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45143ab08253d247db4b1b07dc8205d1aa9691f81904303842d9a66c89bafafb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
