name = "meadow"
author = "broccoli"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7998899711fba79b6bc38ebbae4aef899ab3af6cb4850dbe7d657ded4578a221"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
